subjects=["Hello","Alvi","Hello"]
print(len(subjects))
subjects.append("Alvi")
print(len(subjects))
print(subjects)
subjects.insert(0,"Hi")
print(subjects)
subjects.remove("Hello")
subjects.insert(0,"Hi")
print(subjects)
subjects.remove("Hello")
print(subjects)
alphas=["X","B","A"]
alphas.sort()
print(alphas)
nums=['4','1','5','9']
nums.sort()
print(nums)
numzzz=[9,3,5,6,2]
numzzz.sort()
print(numzzz)
a=[1,3,5,3,2,1,2445]
a.reverse()
print(a)
a.pop()
print(a)
a.clear()
b=a.copy()
print(b)
y=alphas.index("B")
print(y)
alart=[1,3,46,786,67,67,5]
w=alart.count(5)
print(w)
